# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kiven\PycharmProjects\Phishing-email-filter\ui\view\DetectReport.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(963, 737)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(150, 10, 791, 21))
        self.progressBar.setProperty("value", 37)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 121, 16))
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 530, 921, 191))
        self.tableWidget_2.setAutoScroll(False)
        self.tableWidget_2.setAutoScrollMargin(0)
        self.tableWidget_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(3, 1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(225)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 70, 161, 21))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 921, 431))
        self.tableWidget.setAutoScrollMargin(0)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 4, item)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(150, 40, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 121, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Detect Report"))
        self.label_2.setText(_translate("Dialog", "Total Progress"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Subject"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Status"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Result"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Threat Score"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Dialog", "Product change notification: transitioning user groups"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("Dialog", "finished"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("Dialog", "safe"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("Dialog", "0%"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Dialog", "\n"
"紧急！！！"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("Dialog", "processing"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("Dialog", "64%"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Dialog", "\n"
"姚冰"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("Dialog", "waiting"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Dialog", "课程表安排通知\n"
""))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("Dialog", "waiting"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Dialog", "Current Feedback:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "url_basic : have_ip"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "url_basic : netloc_too_long"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "url_basic : have_unusual"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "url_basic : in_phish_tank"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "url_basic : have_redirect"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "url_advance : low_pr"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "url_advance : create_less_3_month"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "html : have_script"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "plain : abnormal_time"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "plain : inducible_title"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "plain : inducible_content"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "Accessory : unusual_size"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "Accessory : trick_type"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Safe"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Dangerous"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Undetected"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Count"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Current Result"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("Dialog", "safe"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("Dialog", "safe"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(5, 4)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget.item(6, 4)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(7, 4)
        item.setText(_translate("Dialog", "safe"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget.item(8, 4)
        item.setText(_translate("Dialog", "safe"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Dialog", "NA"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Dialog", "NA"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("Dialog", "NA"))
        item = self.tableWidget.item(9, 4)
        item.setText(_translate("Dialog", "threatening"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("Dialog", "NA"))
        item = self.tableWidget.item(10, 1)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget.item(10, 2)
        item.setText(_translate("Dialog", "NA"))
        item = self.tableWidget.item(10, 3)
        item.setText(_translate("Dialog", "NA"))
        item = self.tableWidget.item(10, 4)
        item.setText(_translate("Dialog", "processing"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(11, 4)
        item.setText(_translate("Dialog", "waiting"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 1)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 2)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 3)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget.item(12, 4)
        item.setText(_translate("Dialog", "waiting"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Dialog", "紧急！！！"))
        self.label_4.setText(_translate("Dialog", "Email Subject:"))

