# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kiven\PycharmProjects\Phishing-email-filter\ui\view\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1238, 594)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(990, 500, 231, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.import_btn = QtWidgets.QPushButton(self.centralwidget)
        self.import_btn.setGeometry(QtCore.QRect(990, 320, 231, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.import_btn.setFont(font)
        self.import_btn.setObjectName("import_btn")
        self._time = QtWidgets.QLabel(self.centralwidget)
        self._time.setGeometry(QtCore.QRect(1000, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self._time.setFont(font)
        self._time.setObjectName("_time")
        self.check_net_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_net_btn.setGeometry(QtCore.QRect(990, 380, 231, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.check_net_btn.setFont(font)
        self.check_net_btn.setObjectName("check_net_btn")
        self.time_required_label = QtWidgets.QLabel(self.centralwidget)
        self.time_required_label.setGeometry(QtCore.QRect(1120, 260, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.time_required_label.setFont(font)
        self.time_required_label.setObjectName("time_required_label")
        self._net = QtWidgets.QLabel(self.centralwidget)
        self._net.setGeometry(QtCore.QRect(1000, 280, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self._net.setFont(font)
        self._net.setObjectName("_net")
        self.update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_btn.setGeometry(QtCore.QRect(990, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.update_btn.setFont(font)
        self.update_btn.setObjectName("update_btn")
        self.network_status_label = QtWidgets.QLabel(self.centralwidget)
        self.network_status_label.setGeometry(QtCore.QRect(1130, 290, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.network_status_label.setFont(font)
        self.network_status_label.setText("")
        self.network_status_label.setObjectName("network_status_label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(990, 10, 231, 231))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 229, 229))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.plain_cb = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.plain_cb.setGeometry(QtCore.QRect(10, 40, 151, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.plain_cb.setFont(font)
        self.plain_cb.setObjectName("plain_cb")
        self.url_basic_cb = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.url_basic_cb.setGeometry(QtCore.QRect(10, 80, 151, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.url_basic_cb.setFont(font)
        self.url_basic_cb.setObjectName("url_basic_cb")
        self.html_cb = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.html_cb.setGeometry(QtCore.QRect(10, 120, 131, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.html_cb.setFont(font)
        self.html_cb.setObjectName("html_cb")
        self.test_item_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.test_item_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.test_item_label.setFont(font)
        self.test_item_label.setObjectName("test_item_label")
        self.accessory_cb = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.accessory_cb.setGeometry(QtCore.QRect(10, 160, 151, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.accessory_cb.setFont(font)
        self.accessory_cb.setObjectName("accessory_cb")
        self.url_adv_cb = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.url_adv_cb.setGeometry(QtCore.QRect(10, 190, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.url_adv_cb.setFont(font)
        self.url_adv_cb.setObjectName("url_adv_cb")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.email_list_table = QtWidgets.QTableWidget(self.centralwidget)
        self.email_list_table.setEnabled(True)
        self.email_list_table.setGeometry(QtCore.QRect(10, 10, 971, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_list_table.sizePolicy().hasHeightForWidth())
        self.email_list_table.setSizePolicy(sizePolicy)
        self.email_list_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.email_list_table.setObjectName("email_list_table")
        self.email_list_table.setColumnCount(5)
        self.email_list_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.email_list_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.email_list_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.email_list_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.email_list_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.email_list_table.setHorizontalHeaderItem(4, item)
        self.email_list_table.horizontalHeader().setCascadingSectionResizes(True)
        self.email_list_table.horizontalHeader().setDefaultSectionSize(193)
        self.email_list_table.verticalHeader().setStretchLastSection(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.open_eml = QtWidgets.QAction(MainWindow)
        self.open_eml.setObjectName("open_eml")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phishing Email Filter"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.import_btn.setText(_translate("MainWindow", "Mail Import"))
        self._time.setText(_translate("MainWindow", "Time Required："))
        self.check_net_btn.setText(_translate("MainWindow", "Network Status Detection"))
        self.time_required_label.setText(_translate("MainWindow", "0s"))
        self._net.setText(_translate("MainWindow", "Network Status："))
        self.update_btn.setText(_translate("MainWindow", "Update"))
        self.plain_cb.setText(_translate("MainWindow", "Plain Detect"))
        self.url_basic_cb.setText(_translate("MainWindow", "URL Basic Detect"))
        self.html_cb.setText(_translate("MainWindow", "HTML Detect"))
        self.test_item_label.setText(_translate("MainWindow", "Test Item:"))
        self.accessory_cb.setText(_translate("MainWindow", "Accessory Detect"))
        self.url_adv_cb.setText(_translate("MainWindow", "URL Advance Detect"))
        item = self.email_list_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Subject"))
        item = self.email_list_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sender"))
        item = self.email_list_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Receiver"))
        item = self.email_list_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        self.open_eml.setText(_translate("MainWindow", "打开eml文件"))

